openapi: 3.0.2
info:
  title: 'News Portal API'
  version: '0.1'
paths:
  /news:
    get:
      operationId: listNews
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - news
    post:
      operationId: createNews
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Post'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - news
  /news/{id}:
    get:
      operationId: retrieveNews
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this news.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - news
    put:
      operationId: updateNews
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this news.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Post'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - news
    patch:
      operationId: partialUpdateNews
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this news.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Post'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
      - news
    delete:
      operationId: destroyNews
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this news.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - news
  /news/category/{id}:
    get:
      operationId: retrieveNewsByCategory
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this category.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
      tags:
      - category
components:
  schemas:
    Post:
      type: object
      title: Post
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        news_type:
          type: string
          maxLength: 2
        datetime_in:
          type: string
          format: date-time
          readOnly: true
        headline:
          type: string
          maxLength: 128
        content:
          type: string
        post_rating:
          type: integer
          readOnly: true
        author:
          type: object
          title: Author
          readOnly: true
          properties:
            id:
              type: integer
              format: int64
              readOnly: true
            author_rating:
              type: integer
              readOnly: true
            user:
              type: object
              title: User
              properties:
                id:
                  type: integer
                  format: int64
                  readOnly: true
                password:
                  type: string
                  format: password
                  maxLength: 128
                last_login:
                  type: string
                  format: date-time
                  readOnly: true
                is_superuser:
                  type: boolean
                username:
                  type: string
                  maxLength: 150
                last_name:
                  type: string
                  maxLength: 150
                email:
                  type: string
                  format: email
                  maxLength: 254
                is_staff:
                  type: boolean
                is_active:
                  type: boolean
                date_joined:
                  type: string
                  format: date-time
                  readOnly: true
                first_name:
                  type: string
                  maxLength: 150
              required:
                - id
                - username
                - password
          required:
            - id
            - user
        category:
          type: array
          readOnly: true
          uniqueItems: true
          items:
            type: object
            title: Category
            properties:
              id:
                type: integer
                format: int64
                readOnly: true
              name:
                type: string
                maxLength: 20
              subscribers:
                type: array
                uniqueItems: true
                items:
                  type: object
                  title: User
                  properties:
                    id:
                      type: integer
                      format: int64
                      readOnly: true
                    password:
                      type: string
                      format: password
                      maxLength: 128
                    last_login:
                      type: string
                      format: date-time
                      readOnly: true
                    is_superuser:
                      type: boolean
                    username:
                      type: string
                      maxLength: 150
                    last_name:
                      type: string
                      maxLength: 150
                    email:
                      type: string
                      format: email
                      maxLength: 254
                    is_staff:
                      type: boolean
                    is_active:
                      type: boolean
                    date_joined:
                      type: string
                      format: date-time
                      readOnly: true
                    first_name:
                      type: string
                      maxLength: 150
                  required:
                  - id
                  - username
                  - password
            required:
            - id
            - name
      required:
      - id
      - news_type
      - headline
      - content
      - author
      - category
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        author_rating:
          type: integer
          readOnly: true
        user:
          type: object
          readOnly: true
          title: User
          properties:
            id:
              type: integer
              format: int64
              readOnly: true
            password:
              type: string
              format: password
              maxLength: 128
            last_login:
              type: string
              format: date-time
              readOnly: true
            is_superuser:
              type: boolean
            username:
              type: string
              maxLength: 150
            last_name:
              type: string
              maxLength: 150
            email:
              type: string
              format: email
              maxLength: 254
            is_staff:
              type: boolean
            is_active:
              type: boolean
            date_joined:
              type: string
              format: date-time
              readOnly: true
            first_name:
              type: string
              maxLength: 150
          required:
            - id
            - username
            - password
      required:
        - id
        - user
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
          maxLength: 20
        subscribers:
          type: array
          uniqueItems: true
          items:
            type: object
            readOnly: true
            title: User
            properties:
              id:
                type: integer
                format: int64
                readOnly: true
              password:
                type: string
                format: password
                maxLength: 128
              last_login:
                type: string
                format: date-time
                readOnly: true
              is_superuser:
                type: boolean
              username:
                type: string
                maxLength: 150
              last_name:
                type: string
                maxLength: 150
              email:
                type: string
                format: email
                maxLength: 254
              is_staff:
                type: boolean
              is_active:
                type: boolean
              date_joined:
                type: string
                format: date-time
                readOnly: true
              first_name:
                type: string
                maxLength: 150
            required:
              - id
              - username
              - password
      required:
        - id
        - name
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        text:
          type: string
          maxLength: 255
        datetime_on:
          type: string
          format: date-time
          readOnly: true
        comment_rating:
          type: integer
          readOnly: true
        post:
          type: object
          readOnly: true
          title: Post
          properties:
            id:
              type: integer
              format: int64
              readOnly: true
            news_type:
              type: string
              maxLength: 2
            datetime_in:
              type: string
              format: date-time
              readOnly: true
            headline:
              type: string
              maxLength: 128
            content:
              type: string
            post_rating:
              type: integer
              readOnly: true
            author:
              type: object
              title: Author
              properties:
                id:
                  type: integer
                  format: int64
                  readOnly: true
                author_rating:
                  type: integer
                  readOnly: true
                user:
                  type: object
                  title: User
                  properties:
                    id:
                      type: integer
                      format: int64
                      readOnly: true
                    password:
                      type: string
                      format: password
                      maxLength: 128
                    last_login:
                      type: string
                      format: date-time
                      readOnly: true
                    is_superuser:
                      type: boolean
                    username:
                      type: string
                      maxLength: 150
                    last_name:
                      type: string
                      maxLength: 150
                    email:
                      type: string
                      format: email
                      maxLength: 254
                    is_staff:
                      type: boolean
                    is_active:
                      type: boolean
                    date_joined:
                      type: string
                      format: date-time
                      readOnly: true
                    first_name:
                      type: string
                      maxLength: 150
                  required:
                    - id
                    - username
                    - password
              required:
                - id
                - user
            category:
              type: array
              uniqueItems: true
              items:
                type: object
                title: Category
                properties:
                  id:
                    type: integer
                    format: int64
                    readOnly: true
                  name:
                    type: string
                    maxLength: 20
                  subscribers:
                    type: array
                    uniqueItems: true
                    items:
                      type: object
                      title: User
                      properties:
                        id:
                          type: integer
                          format: int64
                          readOnly: true
                        password:
                          type: string
                          format: password
                          maxLength: 128
                        last_login:
                          type: string
                          format: date-time
                          readOnly: true
                        is_superuser:
                          type: boolean
                        username:
                          type: string
                          maxLength: 150
                        last_name:
                          type: string
                          maxLength: 150
                        email:
                          type: string
                          format: email
                          maxLength: 254
                        is_staff:
                          type: boolean
                        is_active:
                          type: boolean
                        date_joined:
                          type: string
                          format: date-time
                          readOnly: true
                        first_name:
                          type: string
                          maxLength: 150
                      required:
                        - id
                        - username
                        - password
                required:
                  - id
                  - name
          required:
            - id
            - news_type
            - headline
            - content
            - author
            - category
        user:
          type: object
          readOnly: true
          title: User
          properties:
            id:
              type: integer
              format: int64
              readOnly: true
            password:
              type: string
              format: password
              maxLength: 128
            last_login:
              type: string
              format: date-time
              readOnly: true
            is_superuser:
              type: boolean
            username:
              type: string
              maxLength: 150
            last_name:
              type: string
              maxLength: 150
            email:
              type: string
              format: email
              maxLength: 254
            is_staff:
              type: boolean
            is_active:
              type: boolean
            date_joined:
              type: string
              format: date-time
              readOnly: true
            first_name:
              type: string
              maxLength: 150
          required:
            - id
            - username
            - password
      required:
        - id
        - text
        - post
        - user
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        password:
          type: string
          format: password
          maxLength: 128
        last_login:
          type: string
          format: date-time
          readOnly: true
        is_superuser:
          type: boolean
        username:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        is_staff:
          type: boolean
        is_active:
          type: boolean
        date_joined:
          type: string
          format: date-time
          readOnly: true
        first_name:
          type: string
          maxLength: 150
      required:
        - id
        - username
        - password
