# Generated by Django 4.2.2 on 2023-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_level_options_alter_level_autumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='connect',
            field=models.TextField(blank=True, null=True, verbose_name='Что соединяет'),
        ),
    ]
