# Generated by Django 4.2.2 on 2023-06-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_rename_img_images_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='data',
            new_name='img',
        ),
    ]
