# Generated by Django 4.2.2 on 2023-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0006_rename_data_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
