# Generated by Django 4.2.2 on 2023-06-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_alter_images_date_added_alter_passage_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.parentareas'),
        ),
    ]
