# Generated by Django 4.2.2 on 2023-06-10 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0008_alter_areas_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='passage',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
