# Generated by Django 4.2.2 on 2023-06-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0011_alter_passage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='pereval.user'),
        ),
    ]
