# Generated by Django 3.2 on 2023-05-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_advertisement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=models.TextField(),
        ),
    ]
