# Generated by Django 3.2 on 2023-05-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20230530_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='updated_at',
        ),
    ]
