# Generated by Django 4.1.7 on 2023-06-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_reply_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
    ]
